### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [adampaulsackfield/adampaulsackfield.github.io-snake#37]
# Feedback

## Requirements

- Pseudocode: DONE
- GitHub Repo:
  - README.md: DONE
  - 15 commits: DONE
- JS code formatted as functions: DONE
- JS code formatted with suitable variable names: DONE
- The code must be your own: DONE
- Click or key press events to trigger the game: DONE
  - No refreshing to start the game again: NOT DONE
    - In main.js line 85 -> `	location.reload();`
- Be responsive and built mobile-first, it should work on different screen widths: ALMOST DONE
  - At the moment there isn't a way to play it on mobile, as your events are set up for key presses.
- Deployed website: DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/02-js/game-marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 40  |
| Code Knowledge & Use | 25 / 25  |
| Readability          | 20 / 20  |
| Responsiveness       | 10 / 15  |
| Total Score          | 95 / 100 |

# Feedback

### Positive

- This project is great Adam! Good going with it!
- I admire your tenacity when it comes to a project, adding, extending and implementing something you have used before is a good way to approach these challenges.
- You are good at communicating with the coaches as well, e.g. you are happy to talk about ideas and things you want to try.
  - This is a great skill when you are in a team you will need to communicate with them.
- In terms of the code it is easy to understand as you have separated your logic into classes and functions.
  - It makes the project soooo much easier to navigate, it is like a big label for what your code does. Thank you :D.
  - I like the comments you have added it may be worth looking into [JS DOC](https://jsdoc.app/).
    - It is a more structured way of documenting your functions and classes.
    - This is what we use in the challenges repo.
- It makes sense for you to use a class for your `Game` and `Snake`, we didn't spend much time on classes but I can see you have a solid understanding of how to use them and why you would want to start to group data and functions together.
- This is one of the most polished games I have had the pleasure of giving feedback on again nice one! :D

### Constructive

- At the moment you can not play it on mobile, the great thing about your code is that you have separated your DOM interaction from your logic by putting it into methods.
  - This means that you can still use your `snake.setDirection()` method you will just need to set it up with a different event.
    - Perhaps you have some arrow buttons at the bottom of the canvas on mobile?
      - The buttons have an id which gets checked and then you call the `snake.setDirection()`
    - Or even go all out and have a mobile keypad where 2, 4, 6 and8 are the arrows ;)
- Remove your `location.reload()`, You should just be able to clear your screen and call your `startGame()`?

- The points below are purely from an outsider's perspective coming into the codebase and making sense of it.

  - Does `this.snakeHead = [150, 150]` have to be an array?
    - You could have it as an object? `this.snakeHead = {x:150, y:150}`
    - This is purely for readability. See the example below.
    ```js
    // Snake.js
    // move()
    // LINE 105
    if (
      this.snakeHead.x > this.width ||
      this.snakeHead.y > this.height ||
      this.snakeHead.x < 0 ||
      this.snakeHead.y < 0 ||
      this.isSnake(this.snakeHead)
    ) {
      return this.gameOver();
    }
    ```
    - If you did that you would have to make `this.snake` an array of objects. Meaning you could do some destructuring when you work with the values.
    ```js
    // Snake.js
    // move()
    // LINE 135
    if (this.snake.length > 3 && !this.isFood()) {
      let { x, y } = this.snake.shift();
      this.updateCanvas("black", x, y);
    }
    ```
  - Side note: Have you tried `console.dir(this)` in your `move()` method?

    - You have to slow the speed down but it is cool to see your object updating and changing :D

  - You probably wouldn't store the variables below in your `Snake.js` file. You would add them as properties of the `Snake` class.
    - You could do something similar with your `Game.js`

  ```js
  // Snake.js
  const score = document.getElementById("score");
  const nomSound = new Audio("./nom.wav");

  // COULD BE EITHER

  // DEFINING THEM IN THE CONSTRUCTOR
  export class Snake extends Game {
    constructor(width, height, name) {
      super(width, height, name);
      this.score = document.getElementById("score");
      this.nomSound = new Audio("./nom.wav");
      // REST OF THE CONSTRUCTOR
    }
  }

  // PASSING THEM IN
  export class Snake extends Game {
    constructor(width, height, name, scoreHTML, nomSound) {
      super(width, height, name);
      this.score = scoreHTML;
      this.nomSound = nomSound;
      // REST OF THE CONSTRUCTOR
    }
  }

  // THIS WAY YOU COULD GIVE IT DIFFERENT THINGS
  // E.G A DIFFERENT SOUND OR DIFFERENT ELEMENT TO UPDATE WITH THE SCORE.
  const snake = new Snake(size, size, user, document.getElementById("score"), new Audio("./nom.wav"));
  ```

---

**Comment by adampaulsackfield** [comment]
Thanks for the feedback. To have another project recognised as one of the most polished is such an honour as I really do put my everything into these projects as I find it such a great learning aid. If I come up with my own project it can be difficult to find the motivation, but if something is a set then I’ll not stop adding to it. 

Some really good feedback here too, I’ll be checking out the JSDocs and making the changes you suggested, particularly in regards to moving some things around for better readability. 

I will also look at adding some buttons for mobile too. 

Again thanks for the awesome feedback, it makes me happy to know that whah I am creating is at least someone usable.
